name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: adopt
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1

      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master

      - name: Run database
        run: docker run --name mysql-sda1 -d --rm -p 3306:3306 -e "MYSQL_ROOT_PASSWORD=mysql" -e "MYSQL_DATABASE=SDA" mysql:latest

      - name: Test
        run: mvn test
