name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1

      - name: Test
        run: mvn test
